### ISSUE TITLE
Add the ability to build from source

### ISSUE THREAD

**Issue by aabounegm** [fizruk/vscode-rzk#41] opened 2023-09-12 20:56 UTC
Currently, the extension prompts to download a pre-built binary from GitHub releases if `rzk` is not found on the system. It should also offer options to install using the different supported build systems: stack, cabal, and nix.
The commands to install look like so (TBC):
- `stack install rzk`
- `cabal v2-install rzk`
- `nix-env -iA rzk`

**Comment by aabounegm** [comment] 2023-09-12 20:58
@deemp Can you please confirm the correctness of the `nix` command?

**Comment by deemp** [comment] 2023-09-12 21:12
There's no top-level `rzk` package in `nixpkgs` ([link](https://search.nixos.org/packages?channel=unstable&show=haskellPackages.rzk&from=0&size=50&sort=relevance&type=packages&query=rzk)). I can probably such an expression.

Then, it'll be possible to install `rzk` with:
- `nix env -iA nixpkgs.rzk` if a person doesn't use Nix flakes;
- `nix profile install nixpkgs#rzk` if a person uses Nix flakes.

**Comment by fizruk** [comment] 2023-09-13 08:50
> There's no top-level `rzk` package in `nixpkgs` ([link](https://search.nixos.org/packages?channel=unstable&show=haskellPackages.rzk&from=0&size=50&sort=relevance&type=packages&query=rzk)).

Maybe it's enough to install `haskellPackages.rzk` via

```sh
nix-env -iA nixpkgs.haskellPackages.rzk
```

?

**Comment by deemp** [comment] 2023-09-13 14:44
@fizruk, when you use this command, you rely on the version of `nixpkgs` present on a user's machine.

```
nix-env -iA nixpkgs.haskellPackages.rzk
```

If a user has flakes enabled, an arbitrary revision of `nixpkgs` can be used for installation.

In a recent revision of the `NixOS/nixpkgs` repository in the `nixpkgs-unstable` branch, the package is marked as broken.

```console
nix shell github:nixos/nixpkgs/f4a33546bdb5f81bd6cceb1b3cb19667145fed83#haskellPackages.rzk

...
error: Package ‘rzk-0.5.3’ in /nix/store/8cf9bhcqh1cw9zgz2q1yh6sxvvpyjal6-source/pkgs/development/haskell-modules/hackage-packages.nix:253017 is marked as broken, refusing to evaluate.
...
```

However, it's possible to get `rzk` in the current shell via

```console
export NIXPKGS_ALLOW_BROKEN=1
nix shell github:nixos/nixpkgs/f4a33546bdb5f81bd6cceb1b3cb19667145fed83#haskellPackages.rzk --impure
```

Or, install it so that `rzk` is available on `PATH` system-wide.

```console
export NIXPKGS_ALLOW_BROKEN=1
nix profile install github:nixos/nixpkgs/f4a33546bdb5f81bd6cceb1b3cb19667145fed83#haskellPackages.rzk --impure
```

Then, you'll have

```console
rzk typecheck --help
Usage: rzk typecheck [STRING]...

Available options:
  -h,--help                Show this help text
```

**Comment by fizruk** [comment] 2023-09-13 16:47
@deemp thanks for the detailed explanation! Do you know why the package is marked as broken?

**Comment by deemp** [comment] 2023-09-13 18:27
No I don't. It's done by automatic tools ([link](https://discourse.nixos.org/t/packages-marked-as-broken-should-come-with-an-explanation/19187/2)).

**Comment by deemp** [comment] 2023-09-13 18:40
UPD on https://github.com/rzk-lang/vscode-rzk/issues/41#issuecomment-1717776034.

I found out it's possible to get `rzk` from an arbitrary revision of `nixpkgs` via old commands ([link](https://nixos.org/manual/nix/unstable/command-ref/nix-shell)).

Make `rzk` available in the current shell:

```console
export NIXPKGS_ALLOW_BROKEN=1
nix-shell -p haskellPackages.rzk -I nixpkgs=https://github.com/NixOS/nixpkgs/archive/f4a33546bdb5f81bd6cceb1b3cb19667145fed83.tar.gz
```

Install system-wide:

```console
export NIXPKGS_ALLOW_BROKEN=1
nix-env -iA nixpkgs.haskellPackages.rzk -I nixpkgs=https://github.com/NixOS/nixpkgs/archive/f4a33546bdb5f81bd6cceb1b3cb19667145fed83.tar.gz
```

Moreover, when flakes are enabled, `rzk` can be obtained from the main repo as there's an `rzk` output ([link](https://github.com/rzk-lang/rzk/blob/5af0e379e5224d9b0f289aa62d7e9ca888cd25b1/flake.nix#L77)). The downside is that we need to prepare a binary cache with pre-built `rzk` so that users don't have to build it.

Without a specific revision:

```console
nix shell github:rzk-lang/rzk#rzk
rzk version

# or, to run
nix run github:rzk-lang/rzk#rzk -- version

# or, to install system-wide
nix profile install github:rzk-lang/rzk#rzk
rzk version
```

The installable ([link](https://nixos.org/manual/nix/unstable/command-ref/new-cli/nix.html#installables)) can be simplified further by renaming the `packages.rzk` output to `packages.default` in the `flake.nix` ([link](https://github.com/rzk-lang/rzk/blob/5af0e379e5224d9b0f289aa62d7e9ca888cd25b1/flake.nix#L77)).

The package will be accessible via `github:rzk-lang/rzk`.

**Comment by aabounegm** [comment] 2023-09-15 23:06
Thanks for such a detailed response!
Do I understand correctly from the last comment that, without flakes enabled, we must refer to a specific revision of nixpkgs and can't simply fetch the latest version? And also, to use the last command that fetches the latest version, is it safe to assume that all Nix users will have flakes enabled?

**Comment by deemp** [comment] 2023-09-18 21:29
> Do I understand correctly from the last comment that, without flakes enabled, we must refer to a specific revision of nixpkgs and can't simply fetch the latest version?

You can fetch the latest version of `nixpkgs` with an old-style command.

```console
nix-shell --packages pan -I nixpkgs=https://github.com/NixOS/nixpkgs/archive/refs/heads/master.zip
```

The problem is that the `nixpkgs` binary cache may be unavailable for the latest commit. That's why, I suggest to use a certain commit for which `rzk` is in the binary cache.

Also, you can provide `rzk` on your own. Here's a sample process
- Build `rzk` in CI from your own flake
- Push `rzk` to a binary cache like [cachix](https://www.cachix.org/)
- Use the latest commit of your flake
- This extension can check whether there's a new version of `rzk` in `cachix`
  - Evaluate the path of the `rzk` package ([link](https://nixos.org/manual/nix/unstable/command-ref/new-cli/nix3-path-info)) 
  - Search "Check the existence of a path in a binary cache" in [link](https://nixos.org/manual/nix/unstable/command-ref/new-cli/nix3-path-info#examples)

> And also, to use the last command that fetches the latest version, is it safe to assume that all Nix users will have flakes enabled?

No, flakes is an experimental feature, so many people don't use it. It can be temporary enabled ([link](https://nixos.wiki/wiki/Flakes#Enable_flakes)).

**Comment by aabounegm** [comment] 2023-09-20 09:28
So the PR is marked as draft because I still didn't understand what's the best set of commands to run 😅 . We would like for it to install the latest available version and not pin to a specific commit so the extension is not tightly coupled with Rzk releases and not have to update it every time a new release is published.
What is the simplest command to achieve this?

> The problem is that the `nixpkgs` binary cache may be unavailable for the latest commit.

If installation via Nix is not as simple as stack/cabal, would you recommend we just remove the option or are there a few commands to run that will achieve what we need?

**Comment by deemp** [comment] 2023-09-20 10:44
> I still didn't understand what's the best set of commands to run

In my opinion, it's the best to let people install `rzk` manually via `nix profile install` ([link](https://nixos.org/manual/nix/unstable/command-ref/new-cli/nix3-profile-install)), `nix-env` ([link](https://nixos.org/manual/nix/unstable/command-ref/nix-env)), `configuration.nix` ([link](https://nixos.wiki/wiki/Overview_of_the_NixOS_Linux_distribution#Declarative_Configuration)) or provide in a `devShell` ([link](https://nixos.wiki/wiki/Flakes#Super_fast_nix-shell)).

So, you can just write in the extension description that `rzk` is a prerequisite and describe installation options for the latest or a specific version.

**Comment by deemp** [comment] 2023-09-20 10:44
> We would like for it to install the latest available version and not pin to a specific commit.

This is possible both with `nix-env` and `nix profile install`. There are two options:
- `nixpkgs` contains the latest versions from Hackage.
- `rzk-lang/rzk` repo provides the latest possible version of `rzk`.

If you want to provide the version from the repo, I suggest to set up caching in your CI to let people use pre-built `rzk`.

- In https://github.com/rzk-lang/rzk/pull/84, I provided the `packages.default` package in `flake.nix`. This is the `rzk` package as a static executable.
- I need you to create a binary cache on cachix and provide credentials as GitHub Actions variable and secret:
  - `CACHIX_CACHE` variable - the name of a binary cache, e.g., `rzk-lang`. 
  - `CACHIX_AUTH_TOKEN` secret - the cache token
- Then, I'll add a step in a GH Action to push `rzk` to that cache so that `rzk` becomes available immediately after release CI

**Comment by aabounegm** [comment] 2023-09-20 12:09
> In my opinion, it's the best to let people install `rzk` manually

I think that makes sense; anyone who knows how to use Nix will most likely not need help installing `rzk`, I believe.
@fizruk Should we just remove the Nix option altogether or is still desirable to have?

**Comment by fizruk** [comment] 2023-09-20 17:21
Sure, I do not mind removing the Nix option from the extension.

**Closed as completed** 2023-09-27 14:52 UTC
